-- ===========================================================================================
-- DEPRECATED: This file has been split into two files for better lock management
-- ===========================================================================================
--
-- Use instead:
--   1. swap_stage_to_live_cutover.sql    — performs the atomic cutover (tight lock)
--   2. cleanup_old_after_swap.sql         — cleans up old tables (separate transaction)
--
-- The old pattern of dropping old tables inside the same transaction as the cutover
-- extended the lock window unnecessarily and reduced rollback options.
--
-- Migration:
-- - refreshGtfsIfNeeded.js now calls swap_stage_to_live_cutover.sql instead
-- - cleanup_old_after_swap.sql is called after optimize_stop_search.sql
--
-- ===========================================================================================
