-- Migration: unique indexes for incremental upsert (ON CONFLICT) on RT tables.
--
-- NO EXTRA INDEXES REQUIRED.
-- Both tables already have primary keys that serve as the ON CONFLICT target:
--   rt_trip_updates          PRIMARY KEY (trip_id)
--   rt_stop_time_updates     PRIMARY KEY (trip_id, stop_sequence)
--
-- ON CONFLICT (trip_id) and ON CONFLICT (trip_id, stop_sequence) resolve
-- against the existing PKs without any additional unique index.
-- This file is kept as a deployment checklist artifact only.
